f = fopen('testFeatures.log', 'w');

runWithFeatures(f, 'good', ...
  				{'maxAngle', 'maxOverlap', 'maxOverlap2', ...
  				 'surf0', 'surf1', 'surf2', 'surf3', 'surf4', 'surf5', ...
  				 'roughness', 'pad_roughness', ...
  				}, 0.1, 5);
